name: todo-api

services:
  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - todo-api-data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpw
      - MYSQL_DATABASE=DEV
      - MYSQL_USER=USER_TODO
      - MYSQL_PASSWORD=secret

volumes:
  todo-api-data-db: