todo-api:
  jwt-secret: "&df0$kC5Iogj=j9"
  jwt-issuer: gabezy-todo-api
swagger:
  title: TODO API
  description: Documentação on-line da API
---
spring:
  application:
    name: Todo-api
  datasource:
    url: jdbc:mysql://localhost:3306/DEV?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: USER_TODO
    password: secret
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 5
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/DEV?allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: root
    password: secretpw
    table: FLYWAY_SCHEMA_HISTORY
springdoc:
  swagger-ui:
    operations-sorter: method
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs
---
logging:
  level:
    sql: info
    root: info