spring:
  datasource:
    url: jdbc:mysql://db-test:3306/TEST?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
    username: USER_TODO
    password: secret
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 5
  flyway:
    enabled: true
    url: jdbc:mysql://db-test:3306/TEST
    user: root
    password: secretpw
    table: FLYWAY_SCHEMA_HISTORY