-- CREATE TABLE --
CREATE TABLE roles
(
    IDT_ROLE BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT 'Role unique ID. Auto increment',
    NAME     VARCHAR(100) NOT NULL UNIQUE COMMENT 'Name of the role'
) ENGINE=InnoDB;