-- CREATE TABLE --
CREATE TABLE user_role
(
    IDT_USER BIGINT NOT NULL COMMENT 'User unique ID (user.IDT_USER).',
    IDT_ROLE BIGINT NOT NULL COMMENT 'Role unique ID (role.IDT_ROLE).',

    CONSTRAINT FK_IDT_USER FOREIGN KEY (IDT_USER) REFERENCES user(IDT_USER),
    CONSTRAINT FK_IDT_ROLE FOREIGN KEY (IDT_ROLE) REFERENCES role(IDT_ROLE)
) ENGINE=InnoDB;