-- CREATE TABLE --
CREATE TABLE user_role
(
    IDT_USER BIGINT NOT NULL COMMENT 'User unique ID (users.IDT_USER).',
    IDT_ROLE BIGINT NOT NULL COMMENT 'Role unique ID (roles.IDT_ROLE).',

    CONSTRAINT FK_IDT_USER FOREIGN KEY (IDT_USER) REFERENCES users(IDT_USER)
        ON DELETE CASCADE ON UPDATE CASCADE ,
    CONSTRAINT FK_IDT_ROLE FOREIGN KEY (IDT_ROLE) REFERENCES roles(IDT_ROLE)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;