ALTER TABLE tasks ADD COLUMN IDT_USER BIGINT COMMENT 'References to user this task belongs.';

ALTER TABLE tasks ADD CONSTRAINT FK_USERS_TASKS
FOREIGN KEY (IDT_USER) REFERENCES users(IDT_USER)
ON DELETE CASCADE
ON UPDATE CASCADE;